server:
  port: 8085
spring:
  datasource: 
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student_application
    username: root
    password: root
  mvc:
   view:
    prefix: /WEB-INF/pages/
    suffix: .jsp
  jpa:
    show-sql: true
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  
